# Copyright (C) 2023 TraceTronic GmbH
#
# SPDX-License-Identifier: MIT

name: '🐛 Bug Report'
description: 'Create a report to help us improve'
labels: ['bug']

body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is about.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps for reproduction
      description: List of steps to reproduce the behavior.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: versions
    attributes:
      label: Versions
      description: Which software versions are affected by the bug?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
  - type: markdown
    attributes:
      value: | 
        **Never report security issues on GitHub or other public channels (Gitter/Twitter/etc.).** 
        Instead, use our [TraceTronic Support Center](https://support.tracetronic.com). For reporting issues 
        containing NDA relevant information please also use our [TraceTronic Support Center](https://support.tracetronic.com).
