# Copyright (C) 2023 TraceTronic GmbH
#
# SPDX-License-Identifier: MIT

name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    name: Update Release Draft
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
