# Copyright (c) 2023-2024 tracetronic GmbH
#
# SPDX-License-Identifier: MIT

name: Release
run-name: Release next product version

on:
  workflow_dispatch:

jobs:
  publish-release-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install poetry
        run: pip3 install poetry
      - name: Set up Python environment
        run: poetry install --only workflow --no-root
      - name: Publish Release
        run: poetry run python ".github/automation_scripts/scripts.py" --name "publish_latest_release_draft --token "${token}"
        env:
          token: ${{ secrets.GH_RELEASE }}

  bump-up-version:
    runs-on: ubuntu-latest
    needs: publish-release-draft
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'main' # otherwise, checks out to tag, which is in detached HEAD state
      - name: Install poetry
        run: pip3 install poetry
      - name: Set up Python environment
        run: poetry install --only workflow --no-root
      - name: Bump up version
        run: poetry run python ".github/automation_scripts/scripts.py" --name "bump_up_version"
      - name: Push changes
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -m "Bump up version"
          git push
